CC=gcc
CXX=g++
RM=rm -f
CPPFLAGS=-g -std=c++17
LDFLAGS=-g
LDLIBS=-lSDL2 -lSDL2_gfx -lSDL2_image -lSDL2_ttf

SRCS=../main.cpp primitives/Rect.cpp wrappers/HeldKey.cpp wrappers/control/Controller.cpp primitives/PointDelta.cpp primitives/Line.cpp wrappers/AppearingText.cpp wrappers/Timer.cpp wrappers/control/CommandBase.cpp wrappers/FpsText.cpp wrappers/control/PlayerMoveCommand.cpp game_entities/CollideBaseGroup.cpp game_entities/BackgroundGroup.cpp BoundedPoint.cpp game_entities/EnemyDrawGroup.cpp primitives/Point.cpp wrappers/AlertText.cpp AlertTextHandler.cpp game_entities/base/EnemyBase.cpp game_entities/Box.cpp
OBJS=$(subst .cpp,.o,$(SRCS))

all: tool

tool: $(OBJS)
	$(CXX) $(LDFLAGS) -o "../Main" $(OBJS) $(LDLIBS) -ggdb3

depend: .depend

.depend: $(SRCS)
	$(RM) ./.depend
	$(CXX) $(CPPFLAGS) -MM $^>>./.depend;

clean:
	$(RM) $(OBJS)

distclean: clean
	$(RM) *~ .depend

include .depend