CC=gcc
CXX=g++
RM=rm -f
CPPFLAGS=-g -std=c++17
LDFLAGS=-g
LDLIBS=-lSDL2 -lSDL2_gfx -lSDL2_image -lSDL2_ttf

SRCS=../main.cpp primatives/Rect.cpp HeldKey.cpp wrappers/control/Controller.cpp PointDelta.cpp primatives/Line.cpp wrappers/Timer.cpp wrappers/control/CommandBase.cpp
OBJS=$(subst .cpp,.o,$(SRCS))

all: tool

tool: $(OBJS)
	$(CXX) $(LDFLAGS) -o "../Main" $(OBJS) $(LDLIBS)

depend: .depend

.depend: $(SRCS)
	$(RM) ./.depend
	$(CXX) $(CPPFLAGS) -MM $^>>./.depend;

clean:
	$(RM) $(OBJS)

distclean: clean
	$(RM) *~ .depend

include .depend